main: su.nightexpress.excellentcrates.CratesPlugin
version: '${project.version}'
name: TwiCrates
authors: [ NightExpress, siberanka ]
description: Secure cross-platform crates with Java resource-pack models and native Bedrock support.
provides: [ ExcellentCrates ]
depend: [ nightcore ]
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - packetevents
  - Geyser-Spigot
  - floodgate
  - BetterModel
  - ModelEngine
  - MythicMobs
  - CraftEngine
api-version: 1.21
